### ISSUE TITLE
v2 alpha release of annotator?

### ISSUE THREAD

**Issue by nikolas** [ikr/annotator-bower#3]
I'm not familiar with bower package administration, but it would be nice to have v2.0.0-alpha.3 of annotator available in bower, since version 1.x isn't compatible with requirejs.

**Comment by ikr** [comment]
Hi @nikolas 

I'm not using bower anymore. But I'll gladly accept a pull request for that; and would even give commit rights to whomever volunteers maintaining ikr/annotator-bower.
